HostsList={ 
      {id="123moviesto", title="123movies.to", type="py"},
      {id="9cartoonme", title="9cartoon.me", type="py"},
      {id="alltubetv", title="alltube.tv", type="py"},
      {id="anyfiles", title="AnyFiles", type="py"},
      {id="appletrailers", title="Apple Trailers", type="py"},
      {id="arconaitvme", title="arconaitv.me", type="py"},
      {id="ardmediathek", title="ARDmediathek", type="py"},
      {id="bajeczkiorg", title="bajeczki.org", type="py"},
      {id="cartoonhd", title="cartoonhd.online", type="py"},
      {id="cdapl", title="cda.pl", type="py"},
      {id="cinemay", title="cinemay.com", type="py"},
      {id="crtankocom", title="crtanko.com", type="py"},
      {id="dailymotion", title="dailymotion.com", type="py"},
      {id="dancetrippin", title="dancetrippin.tv", type="py"},
      {id="dardarkomcom", title="dardarkom.com", type="py"},
      {id="darshowcom", title="darshow.com", type="py"},
      {id="drdk", title="dr.dk", type="py"},
      {id="ekinotv", title="ekino.tv", type="py"},
      {id="ekstraklasatv", title="Ekstraklasa", type="py"},
      {id="eskago", title="eskaGO", type="py"},
      {id="fighttube", title="FightTube", type="py"},
      {id="filma24hdcom", title="filma24hd.com", type="py"},
      {id="filmotopia", title="filmotopia.com", type="py"},
      {id="filmovita", title="filmovita.com", type="py"},
      {id="filmovizijastudio", title="filmovizija.ws", type="py"},
      {id="filmstreamvkcom", title="filmstreamvk.com", type="py"},
      {id="filmy3deu", title="filmy3d.eu", type="py"},
      {id="filmydokumentalneeu", title="FilmyDokumentalne.eu", type="py"},
      {id="filmyto", title="filmy.to", type="py"},
      {id="freediscpl", title="freedisc.pl", type="py"},
      {id="gamatocom", title="gamato-movies.com", type="py"},
      {id="greekdocumentaries3", title="greekdocumentaries3.blogspot.gr", type="py"},
      {id="hdfilmetv", title="hdfilme.tv", type="py"},
      {id="hdkinomir", title="hdkinomir.com", type="py"},
      {id="hitboxtv", title="hitbox.tv", type="py"},
      {id="hoofootcom", title="hoofoot.com", type="py"},
      {id="icefilmsinfo", title="icefilms.info", type="py"},
      {id="iitvpl", title="iitv.pl", type="py"},
      {id="ipla", title="Ipla", type="py"},
      {id="kabarety", title="Kabarety Odpoczywam", type="py"},
      {id="kinopokaz", title="online-kinopokaz.ru", type="py"},
      {id="kinotan", title="Kinotan", type="py"},
      {id="kisscartoonme", title="kisscartoon.me", type="py"},
      {id="kreskoweczki", title="kreskoweczki.pl", type="py"},
      {id="kreskowkazone", title="kreskowkazone.pl", type="py"},
      {id="kwejktv", title="kwejk.tv", type="py"},
      {id="laola1tv", title="laola1.tv", type="py"},
      {id="librestream", title="libre-stream.com", type="py"},
      {id="liveleak", title="LiveLeak.com", type="py"},
      {id="movie4kto", title="movie4k.to", type="py"},
      {id="movienightws", title="movienight.ws", type="py"},
      {id="movizlandcom", title="movizland.com", type="py"},
      {id="musicbox", title="Music-Box", type="py"},
      {id="naszekinoonline", title="nasze-kino.online", type="py"},
      {id="ninateka", title="Ninateka", type="py"},
      {id="onetvod", title="ONET VOD player", type="py"},
      {id="ourmatchnet", title="ourmatch.net", type="py"},
      {id="papystreamingus", title="papystreaming.us", type="py"},
      {id="pinkbike", title="pinkbike.com", type="py"},
      {id="playpuls", title="PlayPuls", type="py"},
      {id="plwwecom", title="pl.wwe.com", type="py"},
      {id="serialnet", title="SerialNet.pl", type="py"},
      {id="serienstreamto", title="serienstream.to", type="py"},
      {id="seriesenstreamingcom", title="series-en-streaming.com", type="py"},
      {id="sovdub", title="sovdub.ru", type="py"},
      {id="sportdeutschland", title="SportDeutschland.TV", type="py"},
      {id="spryciarze", title="Spryciarze", type="py"},
      {id="streamcomplet", title="streamcomplet.com", type="py"},
      {id="streamingseriesxyz", title="Streaming-Series.xyz", type="py"},
      {id="streamliveto", title="StreamLiveTo.tv", type="py"},
      {id="tantifilmorg", title="tantifilm.org", type="py"},
      {id="thewatchseriesto", title="onwatchseries.to", type="py"},
      {id="treetv", title="tree.tv", type="py"},
      {id="tvgrypl", title="tvgry.pl", type="py"},
      {id="tvjworg", title="tv.jw.org", type="py"},
      {id="tvn24", title="TVN 24", type="py"},
      {id="tvnvod", title="TVN Player", type="py"},
      {id="tvproart", title="tvproart.pl", type="py"},
      {id="tvpvod", title="vod.tvp.pl", type="py"},
      {id="twitchtv", title="twitch.tv", type="py"},
      {id="urllist", title="Urllists player", type="py"},
      {id="ustreamtv", title="ustream.tv", type="py"},
      {id="vevo", title="vevo.com", type="py"},
      {id="vumooch", title="vumoo.at", type="py"},
      {id="watchwrestling", title="watchwrestling.tc", type="py"},
      {id="webstream", title="streams player", type="py"},
      {id="wgrane", title="Wgrane.pl", type="py"},
      {id="wptv", title="wp.tv", type="py"},
      {id="wrestlingnetwork", title="wrestlingnetwork.tv", type="py"},
      {id="wrzuta", title="wrzuta.pl", type="py"},
      {id="xrysoise", title="xrysoi.se", type="py"},
      {id="XXX", title="XXX", type="py"},
      {id="yifytv", title="yify.tv", type="py"},
      {id="youtube", title="Youtube player", type="py"},
      {id="zalukajcom", title="zalukaj.com", type="py"},
      {id="zdfmediathek", title="ZDFmediathek", type="py"},
	{id="mykino", title="mykino", fileName="luaHosts/mykino.lua", logoName="luaHosts/mykino.png", type="lua"},
	{id="mytvpro", title="mytvpro", fileName="luaHosts/mytvpro.lua", logoName="luaHosts/mytvpro.png", type="lua"},
	}
