# -*- coding: utf-8 -*-
HostsList=[ 
	("123moviesto", "123movies.to"),
	("9cartoonme", "9cartoon.me"),
	("alltubetv", "alltube.tv"),
	("anyfiles", "AnyFiles"),
	("appletrailers", "Apple Trailers"),
	("arconaitvme", "arconaitv.me"),
	("ardmediathek", "ARDmediathek"),
	("bajeczkiorg", "bajeczki.org"),
	("cartoonhd", "cartoonhd.online"),
	("cdapl", "cda.pl"),
	("cinemay", "cinemay.com"),
	("crtankocom", "crtanko.com"),
	("dailymotion", "dailymotion.com"),
	("dancetrippin", "dancetrippin.tv"),
	("dardarkomcom", "dardarkom.com"),
	("darshowcom", "darshow.com"),
	("drdk", "dr.dk"),
	("ekinotv", "ekino.tv"),
	("ekstraklasatv", "Ekstraklasa"),
	("eskago", "eskaGO"),
	("fighttube", "FightTube"),
	("filma24hdcom", "filma24hd.com"),
	("filmotopia", "filmotopia.com"),
	("filmovita", "filmovita.com"),
	("filmovizijastudio", "filmovizija.ws"),
	("filmstreamvkcom", "filmstreamvk.com"),
	("filmy3deu", "filmy3d.eu"),
	("filmydokumentalneeu", "FilmyDokumentalne.eu"),
	("filmyto", "filmy.to"),
	("freediscpl", "freedisc.pl"),
	("gamatocom", "gamato-movies.com"),
	("greekdocumentaries3", "greekdocumentaries3.blogspot.gr"),
	("hdfilmetv", "hdfilme.tv"),
	("hdkinomir", "hdkinomir.com"),
	("hitboxtv", "hitbox.tv"),
	("hoofootcom", "hoofoot.com"),
	("icefilmsinfo", "icefilms.info"),
	("iitvpl", "iitv.pl"),
	("ipla", "Ipla"),
	("kabarety", "Kabarety Odpoczywam"),
	("kinopokaz", "online-kinopokaz.ru"),
	("kinotan", "Kinotan"),
	("kisscartoonme", "kisscartoon.me"),
	("kreskoweczki", "kreskoweczki.pl"),
	("kreskowkazone", "kreskowkazone.pl"),
	("kwejktv", "kwejk.tv"),
	("laola1tv", "laola1.tv"),
	("librestream", "libre-stream.com"),
	("liveleak", "LiveLeak.com"),
	("movie4kto", "movie4k.to"),
	("movienightws", "movienight.ws"),
	("movizlandcom", "movizland.com"),
	("musicbox", "Music-Box"),
	("naszekinoonline", "nasze-kino.online"),
	("ninateka", "Ninateka"),
	("onetvod", "ONET VOD player"),
	("ourmatchnet", "ourmatch.net"),
	("papystreamingus", "papystreaming.us"),
	("pinkbike", "pinkbike.com"),
	("playpuls", "PlayPuls"),
	("plwwecom", "pl.wwe.com"),
	("serialnet", "SerialNet.pl"),
	("serienstreamto", "serienstream.to"),
	("seriesenstreamingcom", "series-en-streaming.com"),
	("sovdub", "sovdub.ru"),
	("sportdeutschland", "SportDeutschland.TV"),
	("spryciarze", "Spryciarze"),
	("streamcomplet", "streamcomplet.com"),
	("streamingseriesxyz", "Streaming-Series.xyz"),
	("streamliveto", "StreamLiveTo.tv"),
	("tantifilmorg", "tantifilm.org"),
	("thewatchseriesto", "onwatchseries.to"),
	("treetv", "tree.tv"),
	("tvgrypl", "tvgry.pl"),
	("tvjworg", "tv.jw.org"),
	("tvn24", "TVN 24"),
	("tvnvod", "TVN Player"),
	("tvproart", "tvproart.pl"),
	("tvpvod", "vod.tvp.pl"),
	("twitchtv", "twitch.tv"),
	("urllist", "Urllists player"),
	("ustreamtv", "ustream.tv"),
	("vevo", "vevo.com"),
	("vumooch", "vumoo.at"),
	("watchwrestling", "watchwrestling.tc"),
	("webstream", "streams player"),
	("wgrane", "Wgrane.pl"),
	("wptv", "wp.tv"),
	("wrestlingnetwork", "wrestlingnetwork.tv"),
	("wrzuta", "wrzuta.pl"),
	("xrysoise", "xrysoi.se"),
	("XXX", "XXX"),
	("yifytv", "yify.tv"),
	("youtube", "Youtube player"),
	("zalukajcom", "zalukaj.com"),
	("zdfmediathek", "ZDFmediathek"),
	]
